//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinema
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CinemaEntities : DbContext
    {
        public CinemaEntities()
            : base("name=CinemaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<T_Factura> T_Factura { get; set; }
        public virtual DbSet<T_Parametros> T_Parametros { get; set; }
        public virtual DbSet<T_Proyeccion> T_Proyeccion { get; set; }
        public virtual DbSet<T_Reservacion> T_Reservacion { get; set; }
        public virtual DbSet<T_Sala> T_Sala { get; set; }
        public virtual DbSet<T_SalaTipo> T_SalaTipo { get; set; }
        public virtual DbSet<T_Silla> T_Silla { get; set; }
        public virtual DbSet<T_SillaReserva> T_SillaReserva { get; set; }
        public virtual DbSet<T_TipoEstadoReservacion> T_TipoEstadoReservacion { get; set; }
        public virtual DbSet<T_TipoUsuario> T_TipoUsuario { get; set; }
        public virtual DbSet<T_Usuario> T_Usuario { get; set; }
        public virtual DbSet<TGenero> TGenero { get; set; }
        public virtual DbSet<TPelicula> TPelicula { get; set; }
    }
}
