//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinema
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Parametros
    {
        public int Tn_IdParametro { get; set; }
        public string Tt_DescripcionParametro { get; set; }
        public int Tn_Valor { get; set; }
        public Nullable<bool> Tb_Estado { get; set; }
    }
}
