//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinema
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Reservacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_Reservacion()
        {
            this.T_SillaReserva = new HashSet<T_SillaReserva>();
        }
    
        public int Tn_IdReservacion { get; set; }
        public int Tn_IdProyeccion { get; set; }
        public int Tn_IdUsuario { get; set; }
        public int Tn_IdEstadoReserva { get; set; }
        public Nullable<int> Tn_IdFactura { get; set; }
    
        public virtual T_Factura T_Factura { get; set; }
        public virtual T_TipoEstadoReservacion T_TipoEstadoReservacion { get; set; }
        public virtual T_Usuario T_Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_SillaReserva> T_SillaReserva { get; set; }
    }
}
