//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinema
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Silla
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_Silla()
        {
            this.T_SillaReserva = new HashSet<T_SillaReserva>();
        }
    
        public int Tn_IdSilla { get; set; }
        public int Tn_Fila { get; set; }
        public int Tn_Numero { get; set; }
        public int Tn_IdSala { get; set; }
        public Nullable<bool> Tb_Estado { get; set; }
    
        public virtual T_Sala T_Sala { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_SillaReserva> T_SillaReserva { get; set; }
    }
}
