//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinema
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_SillaReserva
    {
        public int Tn_IdSillaReserva { get; set; }
        public int Tn_IdSilla { get; set; }
        public int Tn_IdReservacion { get; set; }
        public int Tn_IdProyeccion { get; set; }
    
        public virtual T_Proyeccion T_Proyeccion { get; set; }
        public virtual T_Reservacion T_Reservacion { get; set; }
        public virtual T_Silla T_Silla { get; set; }
    }
}
