//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinema
{
    using System;
    using System.Collections.Generic;
    
    public partial class TPelicula
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TPelicula()
        {
            this.T_Proyeccion = new HashSet<T_Proyeccion>();
        }
    
        public int Tn_IdPelicula { get; set; }
        public string Tt_NombrePelicula { get; set; }
        public string Tt_NombrePeliculaAdaptado { get; set; }
        public string Tt_Resumen { get; set; }
        public decimal Tn_DuracionMinutos { get; set; }
        public int Tn_IdGenero { get; set; }
        public Nullable<bool> Tb_Estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_Proyeccion> T_Proyeccion { get; set; }
        public virtual TGenero TGenero { get; set; }
    }
}
